lib/dogger_web/router.ex
defmodule DoggerWeb.Router do
  use DoggerWeb, :router

  import DoggerWeb.BusinessAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {DoggerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_business
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DoggerWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", DoggerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: DoggerWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", DoggerWeb do
    pipe_through [:browser, :redirect_if_business_is_authenticated]

    get "/businesses/register", BusinessRegistrationController, :new
    post "/businesses/register", BusinessRegistrationController, :create
    get "/businesses/log_in", BusinessSessionController, :new
    post "/businesses/log_in", BusinessSessionController, :create
    get "/businesses/reset_password", BusinessResetPasswordController, :new
    post "/businesses/reset_password", BusinessResetPasswordController, :create
    get "/businesses/reset_password/:token", BusinessResetPasswordController, :edit
    put "/businesses/reset_password/:token", BusinessResetPasswordController, :update
  end

  scope "/", DoggerWeb do
    pipe_through [:browser, :require_authenticated_business]

    get "/businesses/settings", BusinessSettingsController, :edit
    put "/businesses/settings", BusinessSettingsController, :update
    get "/businesses/settings/confirm_email/:token", BusinessSettingsController, :confirm_email
    resources "/owners", OwnerController
    resources "/pets", PetController
    resources "/stays", StayController
  end

  scope "/", DoggerWeb do
    pipe_through [:browser]

    delete "/businesses/log_out", BusinessSessionController, :delete
    get "/businesses/confirm", BusinessConfirmationController, :new
    post "/businesses/confirm", BusinessConfirmationController, :create
    get "/businesses/confirm/:token", BusinessConfirmationController, :edit
    post "/businesses/confirm/:token", BusinessConfirmationController, :update
  end
end

lib/dogger_web/views/layout_view.ex
defmodule DoggerWeb.LayoutView do
  use DoggerWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/dogger_web/templates/layout/_business_menu.html.heex
<ul>
<%= if @current_business do %>
  <li><%= @current_business.email %></li>
  <li><%= link "Settings", to: Routes.business_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.business_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Register", to: Routes.business_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.business_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/dogger_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/dogger_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/dogger_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Dogger", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap');
    </style>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
          <%= render "_business_menu.html", assigns %>
        </nav>
        <a href="/" class="dogger-logo">
          <img src={Routes.static_path(@conn, "/images/dogger.png")} alt="Dogger Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>